export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const DELETE_POSTS = 'DELETE_POSTS';
export const CREATE_POSTS = 'CREATE_POSTS';
export const EDIT_POST = 'EDIT_POST';
export const SORT_POST = 'SORT_POST';
export const VOTE_POST = 'VOTE_POST';


export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const EDIT_COMMENTS = 'EDIT_COMMENTS';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';


export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';