export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const DELETE_POSTS = 'DELETE_POSTS';
export const CREATE_POSTS = 'CREATE_POSTS';

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';


export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';